<a href="https://colab.research.google.com/github/MarcoZambrano/Inteligencia-Artificial-IA-/blob/main/LECCION8JULIODEL2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
import numpy as np
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
vector = np.random.rand(10)
vector[np.argmax(vector)] = 0
print(vector)

[0.14186504 0.24910488 0.55159594 0.         0.84598837 0.05940593
 0.45702703 0.51520962 0.71630612 0.11336464]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,2])



8


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
subarray = arr[2:5]
print(subarray)

[3 4 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
ultimos_cuatro = arr[-4:]
print(ultimos_cuatro)

[4 5 6 7]


In [ ]:
import numpy as np
matriz = np.ones((3, 3), dtype=bool)
print(matriz)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
impa = [x for x in arr if x % 2 != 0]
print(impa)


[1, 3, 5, 7, 9]


In [ ]:
import numpy as np
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5])
invertido = vector[::-1]
print(invertido)


[5 4 3 2 1]


In [ ]:
import numpy as np
aleatoria = np.random.randint(1, 101, size=(10, 10))
minimo = aleatoria.min()
maximo = aleatoria.max()
print("MATRIZ ALEATORIA:")
print(aleatoria)

print(f"\nVALOR MINIMO: {minimo}")
print(f"VALOR MAXIMO: {maximo}")


MATRIZ ALEATORIA:
[[ 88  16   3  64   8   1  10  74  35  76]
 [ 10  23  88  72  65  14   1  73  71  90]
 [ 20  22  35  24  59  16   6  16  85  21]
 [  5  45  55  35  99  17  83  44   5  54]
 [ 39  54  21  88   6  42  81  72  17  21]
 [ 58  90  19  21  35  37  60  33  75  33]
 [ 99  46  42  98  13 100  26   2  63  17]
 [ 80  54  40  71  16  74  11  84  76  71]
 [100  56  33  36  53  77  66  85  59  94]
 [ 27  34  76  11  85  65  77  81  81  12]]

VALOR MINIMO: 1
VALOR MAXIMO: 100


In [ ]:
import numpy as np
matriz = np.random.randint(1, 101, size=(3, 3, 3))

print("MATRIZ:")
print(matriz)


MATRIZ:
[[[12 75 87]
  [56 59 17]
  [90 81 23]]

 [[84 96 22]
  [51 64 80]
  [88 93 49]]

 [[35 41 85]
  [97 99 25]
  [77 96 99]]]


In [ ]:
import numpy as np
aleatoria = np.random.randint(1, 101, size=(10, 10))
contador = 1
for i in range(aleatoria.shape[0]):
    for j in range(aleatoria.shape[1]):
        if aleatoria[i, j] % 2 != 0:
            aleatoria[i, j] = -1
            contador += 1

print("Matriz con impares reemplazados:")
print(aleatoria)

Matriz con impares reemplazados:
[[76 -1 -1 30 92 -1 16  6 12 -1]
 [50 78 90 30 50 -1 -1 22 20  2]
 [-1 42 54 -1 -1 -1 54 -1 92 24]
 [60 28 70 -1 -1 -1 76 96 -1 62]
 [-1 -1 -1 -1 -1 82 -1 34 -1 36]
 [16 66 90 -1 -1  2 -1 -1 -1 -1]
 [96 -1 32 -1 20 -1 54 -1 34 -1]
 [-1  4 -1 -1 70 20 28 -1 -1 96]
 [-1 -1 -1 58 -1 -1 -1 72 58 96]
 [44 -1 -1 -1 -1 -1 14  2 -1 -1]]


In [3]:
import numpy as np
mi_arreglo = np.array([1.5, 2.7, 3.14])
ceros = np.zeros(5)
aleatorios = np.random.rand(4)

print(mi_arreglo)
print(ceros)
print(aleatorios)


[1.5  2.7  3.14]
[0. 0. 0. 0. 0.]
[0.60056361 0.25961088 0.40909226 0.94450583]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr.reshape(2, -1)

print(arr_2d)


[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(Z1, Z2)

print(common_values)


[5 6 7 8]


In [9]:
import numpy as np

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

are_equal = np.array_equal(A, B)

print("Las matrices son iguales:", are_equal)


Las matrices son iguales: False


In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_array = np.vstack((a, b))

print(stacked_array)


[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_array = np.hstack((a, b))

print(stacked_array)


[1 2 3 4 5 6]


In [12]:
import numpy as np

tmp = np.arange(15)

result = tmp[(tmp >= 5) & (tmp < 10)]

print(result)


[5 6 7 8 9]


In [14]:
import numpy as np

def pair_max(x, y):
  """Obtiene el máximo de elementos correspondientes en dos matrices."""
  return np.maximum(x, y)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)


[6 7 9 8 9 7 5]


In [15]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Matriz original:")
print(arr)

arr[:, [0, 1]] = arr[:, [1, 0]]

print("Matriz después de intercambiar las columnas 1 y 2:")
print(arr)


Matriz original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matriz después de intercambiar las columnas 1 y 2:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [16]:
import numpy as np

arr = np.random.uniform(5, 10, size=(5, 3))

print(arr)


[[5.10357975 7.96618949 9.9445103 ]
 [5.3658359  8.99770481 5.31942664]
 [5.27803527 7.83430955 8.85738947]
 [6.19627903 6.64768213 5.89642944]
 [5.5452411  7.90639595 9.42324867]]
