<a href="https://colab.research.google.com/github/MarcoZambrano/Inteligencia-Artificial-IA-/blob/main/LECCION8JULIODEL2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.__version__)

1.25.2


In [7]:
import numpy as np
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
import numpy as np
vector = np.random.rand(10)
vector[np.argmax(vector)] = 0
print(vector)

[0.14186504 0.24910488 0.55159594 0.         0.84598837 0.05940593
 0.45702703 0.51520962 0.71630612 0.11336464]


In [15]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,2])



8


In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
subarray = arr[2:5]
print(subarray)

[3 4 5]


In [17]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
ultimos_cuatro = arr[-4:]
print(ultimos_cuatro)

[4 5 6 7]


In [19]:
import numpy as np
matriz = np.ones((3, 3), dtype=bool)
print(matriz)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
impa = [x for x in arr if x % 2 != 0]
print(impa)


[1, 3, 5, 7, 9]


In [21]:
import numpy as np
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [22]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5])
invertido = vector[::-1]
print(invertido)


[5 4 3 2 1]


In [32]:
import numpy as np
aleatoria = np.random.randint(1, 101, size=(10, 10))
minimo = aleatoria.min()
maximo = aleatoria.max()
print("MATRIZ ALEATORIA:")
print(aleatoria)

print(f"\nVALOR MINIMO: {minimo}")
print(f"VALOR MAXIMO: {maximo}")


MATRIZ ALEATORIA:
[[ 88  16   3  64   8   1  10  74  35  76]
 [ 10  23  88  72  65  14   1  73  71  90]
 [ 20  22  35  24  59  16   6  16  85  21]
 [  5  45  55  35  99  17  83  44   5  54]
 [ 39  54  21  88   6  42  81  72  17  21]
 [ 58  90  19  21  35  37  60  33  75  33]
 [ 99  46  42  98  13 100  26   2  63  17]
 [ 80  54  40  71  16  74  11  84  76  71]
 [100  56  33  36  53  77  66  85  59  94]
 [ 27  34  76  11  85  65  77  81  81  12]]

VALOR MINIMO: 1
VALOR MAXIMO: 100


In [34]:
import numpy as np
matriz = np.random.randint(1, 101, size=(3, 3, 3))

print("MATRIZ:")
print(matriz)


MATRIZ:
[[[12 75 87]
  [56 59 17]
  [90 81 23]]

 [[84 96 22]
  [51 64 80]
  [88 93 49]]

 [[35 41 85]
  [97 99 25]
  [77 96 99]]]


In [35]:
import numpy as np
aleatoria = np.random.randint(1, 101, size=(10, 10))
contador = 1
for i in range(aleatoria.shape[0]):
    for j in range(aleatoria.shape[1]):
        if aleatoria[i, j] % 2 != 0:
            aleatoria[i, j] = -1
            contador += 1

print("Matriz con impares reemplazados:")
print(aleatoria)

Matriz con impares reemplazados:
[[76 -1 -1 30 92 -1 16  6 12 -1]
 [50 78 90 30 50 -1 -1 22 20  2]
 [-1 42 54 -1 -1 -1 54 -1 92 24]
 [60 28 70 -1 -1 -1 76 96 -1 62]
 [-1 -1 -1 -1 -1 82 -1 34 -1 36]
 [16 66 90 -1 -1  2 -1 -1 -1 -1]
 [96 -1 32 -1 20 -1 54 -1 34 -1]
 [-1  4 -1 -1 70 20 28 -1 -1 96]
 [-1 -1 -1 58 -1 -1 -1 72 58 96]
 [44 -1 -1 -1 -1 -1 14  2 -1 -1]]


In [ ]:
import numpy as np
arr_float : np.array([1.5, 3.2, 4.7, 5.1], dtype=np.float32)
print(f"TIPO DE ARRAY: ")