<a href="https://colab.research.google.com/github/MarcoZambrano/Inteligencia-Artificial-IA-/blob/main/LibraryAlgebraLineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as algebraLineal

a=algebraLineal.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])
a[1] = 888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [10]:
import numpy as np
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b[1:,1:]
print(aux.shape)
print(aux)

print('BEFORE/.....')
print(b)
print(aux)

aux[1,1]=1000

print('AFTER/.....')
print(b)
print(aux)

(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
BEFORE/.....
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
AFTER/.....
[[   1    2    3]
 [  11   22   33]
 [ 111  222 1000]]
[[  22   33]
 [ 222 1000]]


In [14]:
c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [17]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
g=np.random.random((5,5))
print(g)

[[0.11756024 0.06368955 0.98586156 0.92181354 0.63692989]
 [0.56616486 0.46456553 0.46878598 0.55162078 0.78123697]
 [0.77059644 0.88878328 0.90030461 0.17907781 0.27012851]
 [0.69053242 0.56946445 0.79900904 0.77781356 0.58490291]
 [0.90883989 0.88197874 0.20516416 0.41934438 0.9771752 ]]


In [29]:
tmp1=np.random.randint(1,20,(4,4))
print(tmp1)
rows=np.array((0,1,2,3))
cols=np.arange(4)
print(rows)
print(cols)
print(rows.shape)
print(cols.shape)

tmp1[rows,cols]=100
print(tmp1)

[[11 10 11  1]
 [ 9  1  8 13]
 [ 1 18  7  5]
 [ 7 16  7 13]]
[0 1 2 3]
[0 1 2 3]
(4,)
(4,)
[[100  10  11   1]
 [  9 100   8  13]
 [  1  18 100   5]
 [  7  16   7 100]]


In [43]:
import numpy as np
tmp1= np.random.randint(20, 50, size=(6, 6))
print(tmp1)

[[21 26 29 33 34 45]
 [22 37 41 49 44 45]
 [20 21 28 47 24 49]
 [30 24 33 38 21 46]
 [48 35 22 23 36 46]
 [34 47 36 47 36 22]]


In [44]:
filter=(tmp1>45)
print(filter)
print(tmp1[filter])

[[False False False False False False]
 [False False False  True False False]
 [False False False  True False  True]
 [False False False False False  True]
 [ True False False False False  True]
 [False  True False  True False False]]
[49 47 49 46 48 46 47 47]


In [48]:
tmp1= np.random.randint(1, 100,(10,10))
print(tmp1)

[[21 21 85 73 21 78 84 68  5 37]
 [27 28 50 69 90 89 18 26 73 26]
 [70  9 73 10 92 25 55 82 49 65]
 [67 14 59 18 10 69 40 85 16 17]
 [23 70 60 17 81 19 14 66 90 83]
 [32 20 36 12  3 13 24 53 83 64]
 [86 72 57  9 73 15  3 14 78 79]
 [43 32 72 63 12 47 96 68 86 29]
 [51 91 37 40 78 83 40 86 61 20]
 [18 47 64 73 17 41 65 43 16 28]]


In [51]:
filter= (tmp1 % 2 == 0)
print(filter)
print(tmp1[filter])

[[False False False False False  True  True  True False False]
 [False  True  True False  True False  True  True False  True]
 [ True False False  True  True False False  True False False]
 [False  True False  True  True False  True False  True False]
 [False  True  True False False False  True  True  True False]
 [ True  True  True  True False False  True False False  True]
 [ True  True False False False False False  True  True False]
 [False  True  True False  True False  True  True  True False]
 [False False False  True  True False  True  True False  True]
 [ True False  True False False False False False  True  True]]
[78 84 68 28 50 90 18 26 26 70 10 92 82 14 18 10 40 16 70 60 14 66 90 32
 20 36 12 24 64 86 72 14 78 32 72 12 96 68 86 40 78 40 86 20 18 64 16 28]


In [54]:
tmp3=np.array([1,2,3,4,5], dtype=np.float64)
print(tmp3.dtype)

float64


In [57]:
x=np.array([[1,2],[11,22]])
y=np.array([[22,33],[44,55]])
print(x)
print(y)

print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide (x,y))

[[ 1  2]
 [11 22]]
[[22 33]
 [44 55]]
[[-21 -31]
 [-33 -33]]
[[  22   66]
 [ 484 1210]]
[[0.04545455 0.06060606]
 [0.25       0.4       ]]


In [60]:
tmp1= np.random.randint(1, 10,(2,5))
print(tmp1)
aux=tmp1.mean()
print(aux)

[[2 6 2 8 8]
 [2 5 6 9 6]]
5.4


In [62]:
print(tmp1.mean(axis=1))
print(tmp1.mean(axis=0))

[5.2 5.6]
[2.  5.5 4.  8.5 7. ]
